# https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
wx:
  config:
    appId: "wx2e650cc251405cad"
    appSecret: "0c854ee5724d4be1816de6e6fe9714d6"
    #???Id
    templateId1: "ssO-btRIoKAzlOFwJDTF1xLWF2h1PyW4Ko_TKhlJYBA"
    openidList:
      - "oWoxv5zCn54YSdUMr1fctPVpsAm4"
      - "oWoxv5_tlbYCXCNqw_sITP2Y6C64"

message:
  config:
    birthday1: "06-19"
    birthday2: "10-15"
    togetherDate: "2020-12-10"
    message: "Have a happy day and love you"

# https://tianqiapi.com/user/login
weather:
  config:
    appid: "12785967"
    appSecret: "QkQ4dx38   "
    city: "榆林"
# https://www.apispace.com/eolink/api/myjj/introduction
ApiSpace:
  token: "7q0an6ajb4fcqkf002zwra0ozlzvnkff"

server:
  port: 8088

